name: crud_getxcli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_launcher_icons: 0.9.2
  http: 0.13.4
  get_storage: 2.0.3
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

flutter_icons:
  android: launcher_icon
  image_path: assets/images/logo.jpg
  ios: true

get_cli:
  separator: .
  sub_folder: false

