name: crud_getxcli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: 0.13.4
  get_storage: 2.0.3
  intl: 0.17.0
  firebase_core: 1.13.1
  firebase_auth: 3.3.11
  flutter_svg: 1.0.3
  google_fonts: 2.3.1
  animated_splash_screen: 1.1.0
  image_picker: 0.8.5
  geolocator: 8.2.1
  #google_maps_flutter: 2.1.5
  geocoding: 2.0.4
  dio: 4.0.6
  flutter: 
    sdk: flutter
  #flutter_launcher_icons: 0.9.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_test: 
    sdk: flutter


# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/logo.png"
# flutter_icons:
#   image_path: "assets/images/logo.png"
#   image_path_android:  "assets/images/logo.jpg"
#   android: "launcher_icon"
#   ios: true
#   remove_alpha_ios: true

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"


flutter: 
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true



get_cli:
  separator: .
  sub_folder: false

